"""Profile an exported source dataset and write a *source data dictionary* (YAML).

The dictionary describes the export without its data: tables, columns, types, null rates,
distinct counts, and code lists for low-cardinality code columns. It is what a person or an AI agent
reads to write mapping SQL, so it can be shared where the data itself cannot.

Values are only listed for columns that look like code lists: at most `max_codes` distinct values,
each at most 40 characters, not purely numeric (amounts), and a name that does not suggest personal or
free-text data. Distinct counts are approximate (HyperLogLog). The customer
completes the `description` fields and reviews the file before sharing it.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from .duck import quote_ident, quote_str, sandboxed_connection

# Columns whose values are never listed, whatever their cardinality.
SENSITIVE = re.compile(r"(name|address|street|city|postcode|zip|phone|email|iban|national_code|tax_id|"
                       r"birth|passport|narrative|description|comment|note|reference|_ref$|document)", re.I)
_NUMERIC = re.compile(r"^-?[0-9]+(\.[0-9]+)?$")
_TYPE = {"VARCHAR": "string", "BIGINT": "integer", "BOOLEAN": "boolean", "DOUBLE": "decimal", "DATE": "date"}


def discover_tables(export_dir: Path) -> dict[str, dict[str, str]]:
    """Find source tables in an export.

    A folder is one table if it holds Hive partitions (``key=value`` sub-folders) or files named
    ``part-*`` / ``data_*``. Any other data file is a table of its own, named after the file
    (e.g. ``reference/entity.csv`` -> ``entity``). Hidden and ``_``-prefixed paths are ignored.
    """
    tables: dict[str, dict[str, str]] = {}
    for p in sorted(export_dir.rglob("*")):
        ext = p.suffix.lower()
        rel = p.relative_to(export_dir)
        if ext not in (".csv", ".parquet") or any(part.startswith((".", "_")) for part in rel.parts):
            continue
        parts = list(rel.parts)
        hive = next((i for i, x in enumerate(parts) if "=" in x), None)
        if hive is not None:
            table_dir = Path(*parts[:hive])
        elif p.name.startswith(("part-", "part_", "data_")) and len(parts) > 1:
            table_dir = Path(*parts[:-1])
        else:
            tables.setdefault(p.stem, {"path": str(rel), "format": ext.lstrip(".")})
            continue
        tables.setdefault(table_dir.name, {"path": f"{table_dir}/**/*{ext}", "format": ext.lstrip(".")})
    return tables


def profile_export(export_dir: Path | str, output: Path | str, max_codes: int = 30,
                   list_codes: bool = True, types_file: str | None = None) -> dict[str, Any]:
    export_dir = Path(export_dir).resolve()
    con = sandboxed_connection([export_dir])
    types = json.loads((export_dir / types_file).read_text()) if types_file else {}
    doc: dict[str, Any] = {
        "source": export_dir.name,
        "profiled_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "note": "Generated by sora-tools profile. Complete the descriptions and review before sharing.",
        "tables": {},
    }
    for name, t in discover_tables(export_dir).items():
        glob = quote_str(str(export_dir / t["path"]))
        reader = (f"read_parquet({glob}, union_by_name = true, hive_partitioning = false)" if t["format"] == "parquet"
                  else f"read_csv({glob}, union_by_name = true, hive_partitioning = false, header = true)")
        con.execute(f"CREATE OR REPLACE TEMP TABLE t AS SELECT * FROM {reader}")  # read once
        n = con.execute("SELECT count(*) FROM t").fetchone()[0]
        files = len(list(export_dir.glob(t["path"])))
        described = con.execute("DESCRIBE t").fetchall()
        aggs = ", ".join(f"count(*) - count({quote_ident(c)}), approx_count_distinct({quote_ident(c)})" for c, *_ in described)
        stats = con.execute(f"SELECT {aggs} FROM t").fetchone() if described else ()
        cols = {}
        for i, (col, dtype, *_) in enumerate(described):
            q = quote_ident(col)
            nulls, distinct = stats[2 * i], stats[2 * i + 1]
            declared = types.get(name, {}).get(col)
            c: dict[str, Any] = {
                "type": {"str": "string", "int": "integer", "bool": "boolean"}.get(declared, _TYPE.get(dtype.split("(")[0], dtype.lower())),
                "description": "",
                "null_rate": round(nulls / n, 4) if n else None,
                "distinct_approx": distinct,
            }
            if list_codes and 0 < distinct <= max_codes and not SENSITIVE.search(col) and c["type"] not in ("decimal", "date"):
                vals = [r[0] for r in con.execute(
                    f"SELECT CAST({q} AS VARCHAR) v FROM t WHERE {q} IS NOT NULL GROUP BY v ORDER BY v LIMIT {max_codes + 1}").fetchall()]
                numeric = all(_NUMERIC.match(v) for v in vals)
                if len(vals) <= max_codes and all(len(v) <= 40 for v in vals) and not numeric:
                    c["codes"] = {v: "" for v in vals}
            cols[col] = c
        doc["tables"][name] = {"description": "", "path": t["path"], "format": t["format"], "files": files,
                               "rows": n, "columns": cols}
    Path(output).write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=120))
    return doc
